// Operator Console -- "ui": the analyst's connect script and the Add
// person assistant (design/adr/0039-script-de-conexao-do-analista.md).
//
// Adding a person ends the way adding an agent ends in a SIEM manager: with
// one command, or one downloadable script, the new analyst runs on their
// own machine. It checks for Claude Code, trusts the deployment's private
// CA when there is one, checks the gateway answers, and registers the
// gateway in Claude Code with the OAuth client the IdP knows. It carries
// nothing secret: the endpoint, a public client id, a callback port and a
// CA certificate. The one-time password travels separately.

package main

import (
	"bytes"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strings"
	"text/template"
	"time"
	"unicode"

	"github.com/bunnyiesart/Gatte/internal/config"
	"github.com/bunnyiesart/Gatte/internal/idp"
	"github.com/bunnyiesart/Gatte/internal/visible"
)

// connectInfo is what a connect script is made of.
type connectInfo struct {
	Ready    bool
	Missing  string
	URL      string
	MetaURL  string
	ClientID string
	Port     int
	Server   string
	Username string
	CAPEM    string
	Date     string
}

var uiSafeURLRe = regexp.MustCompile(`^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?(/[A-Za-z0-9._~/-]*)?$`)

// uiConnectInfo reads what the scripts need from the configuration. Every
// value it returns is safe inside single quotes in sh and PowerShell: the
// URL, names and client id are held to charsets without quotes, and the CA
// is parsed and re-encoded, so it can only be base64 lines.
func uiConnectInfo(cfg *config.Config, username string, now time.Time) (connectInfo, error) {
	c := connectInfo{Server: cfg.Connect.ServerName, ClientID: cfg.Connect.ClientID, Port: cfg.Connect.CallbackPort,
		URL: cfg.OIDC.Audience, Date: now.UTC().Format("2006-01-02")}
	if c.Server == "" {
		c.Server = "gatte"
	}
	if c.ClientID == "" {
		c.Missing = "Set [connect] client_id and callback_port in the configuration file: the public OAuth client your identity provider has registered for Claude Code, and the port of its redirect URI."
		return c, nil
	}
	if !uiSafeURLRe.MatchString(c.URL) {
		return c, fmt.Errorf("oidc.audience %q cannot go into a connect script: it must be a plain https URL", c.URL)
	}
	u, _ := url.Parse(c.URL)
	c.MetaURL = u.Scheme + "://" + u.Host + "/.well-known/oauth-protected-resource"
	if username != "" {
		if err := idp.ValidateAccount(idp.Account{Username: username, DisplayName: "x"}); err != nil {
			return c, err
		}
		c.Username = username
	}
	if cfg.Connect.CAFile != "" {
		pemText, err := uiCanonicalCA(cfg.Connect.CAFile)
		if err != nil {
			return c, err
		}
		c.CAPEM = pemText
	}
	c.Ready = true
	return c, nil
}

// uiCanonicalCA reads a PEM file and returns only its certificates,
// re-encoded: nothing else in the file reaches a script.
func uiCanonicalCA(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("connect.ca_file: %w", err)
	}
	var out bytes.Buffer
	for {
		var blk *pem.Block
		blk, b = pem.Decode(b)
		if blk == nil {
			break
		}
		if blk.Type != "CERTIFICATE" {
			continue
		}
		if _, err := x509.ParseCertificate(blk.Bytes); err != nil {
			return "", fmt.Errorf("connect.ca_file: %w", err)
		}
		if err := pem.Encode(&out, &pem.Block{Type: "CERTIFICATE", Bytes: blk.Bytes}); err != nil {
			return "", err
		}
	}
	if out.Len() == 0 {
		return "", errors.New("connect.ca_file: no certificate in it")
	}
	return out.String(), nil
}

var shScript = template.Must(template.New("sh").Parse(`#!/bin/sh
# Connect Claude Code to Gatte, the team's MCP gateway.
{{if .Username}}# For {{.Username}}. {{end}}Generated by mcp-gateway ui on {{.Date}}. Contains no secret.
set -eu

GATTE_URL='{{.URL}}'

say() { printf '%s\n' "$*"; }

if ! command -v claude >/dev/null 2>&1; then
  say "Claude Code isn't installed. Install it, then run this script again:"
  say "  https://docs.claude.com/en/docs/claude-code/setup"
  exit 1
fi
{{if .CAPEM}}
# The gateway's certificate comes from the team's own certificate authority.
GATTE_DIR="$HOME/.config/gatte"
mkdir -p "$GATTE_DIR"
cat > "$GATTE_DIR/ca.pem" <<'GATTE_CA'
{{.CAPEM}}GATTE_CA
export NODE_EXTRA_CA_CERTS="$GATTE_DIR/ca.pem"
added=no
for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
  [ -f "$rc" ] || continue
  if ! grep -q 'gatte/ca.pem' "$rc"; then
    printf '\n# Gatte: trust the team certificate authority\nexport NODE_EXTRA_CA_CERTS="$HOME/.config/gatte/ca.pem"\n' >> "$rc"
  fi
  added=yes
done
if [ "$added" = no ]; then
  printf '# Gatte: trust the team certificate authority\nexport NODE_EXTRA_CA_CERTS="$HOME/.config/gatte/ca.pem"\n' >> "$HOME/.profile"
fi
say "✓ Trusted the team certificate authority"
{{end}}
if command -v curl >/dev/null 2>&1; then
  if curl -fsS{{if .CAPEM}} --cacert "$GATTE_DIR/ca.pem"{{end}} -o /dev/null --max-time 10 '{{.MetaURL}}'; then
    say "✓ Gatte answers at $GATTE_URL"
  else
    say "! Gatte didn't answer at $GATTE_URL. Are you on the VPN? Continuing anyway."
  fi
fi

claude mcp remove '{{.Server}}' --scope user >/dev/null 2>&1 || true
claude mcp add --transport http --scope user --client-id '{{.ClientID}}' --callback-port {{.Port}} '{{.Server}}' "$GATTE_URL"

say ""
say "✓ Done. Next: open a new terminal, run claude, type /mcp, choose {{.Server}}{{if .Username}},"
say "  and sign in as {{.Username}}{{end}}."
`))

var ps1Script = template.Must(template.New("ps1").Parse(`# Connect Claude Code to Gatte, the team's MCP gateway.
{{if .Username}}# For {{.Username}}. {{end}}Generated by mcp-gateway ui on {{.Date}}. Contains no secret.
# Run: powershell -ExecutionPolicy Bypass -File .\connect-gatte.ps1
$ErrorActionPreference = 'Stop'

$GatteUrl = '{{.URL}}'

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
  Write-Host "Claude Code isn't installed. Install it, then run this script again:"
  Write-Host "  https://docs.claude.com/en/docs/claude-code/setup"
  exit 1
}
{{if .CAPEM}}
# The gateway's certificate comes from the team's own certificate authority.
$GatteDir = Join-Path $env:USERPROFILE '.gatte'
New-Item -ItemType Directory -Force -Path $GatteDir | Out-Null
$Ca = Join-Path $GatteDir 'ca.pem'
@'
{{.CAPEM}}'@ | Set-Content -Path $Ca -Encoding ascii
[Environment]::SetEnvironmentVariable('NODE_EXTRA_CA_CERTS', $Ca, 'User')
$env:NODE_EXTRA_CA_CERTS = $Ca
Write-Host "Trusted the team certificate authority"
{{else}}
try {
  Invoke-WebRequest -UseBasicParsing -TimeoutSec 10 -Uri '{{.MetaURL}}' | Out-Null
  Write-Host "Gatte answers at $GatteUrl"
} catch {
  Write-Host "Gatte didn't answer at $GatteUrl. Are you on the VPN? Continuing anyway."
}
{{end}}
claude mcp remove '{{.Server}}' --scope user 2>$null | Out-Null
claude mcp add --transport http --scope user --client-id '{{.ClientID}}' --callback-port {{.Port}} '{{.Server}}' $GatteUrl

Write-Host ""
Write-Host "Done. Next: open a new terminal, run claude, type /mcp, choose {{.Server}}{{if .Username}}, and sign in as {{.Username}}{{end}}."
`))

// uiConnectCommand is the one line for a machine that needs no CA.
func uiConnectCommand(c connectInfo) string {
	return fmt.Sprintf("claude mcp add --transport http --scope user --client-id '%s' --callback-port %d '%s' '%s'", c.ClientID, c.Port, c.Server, c.URL)
}

func uiRenderScript(c connectInfo, os string) (string, string, error) {
	var b bytes.Buffer
	switch os {
	case "macos", "linux":
		if err := shScript.Execute(&b, c); err != nil {
			return "", "", err
		}
		return b.String(), "connect-gatte.sh", nil
	case "windows":
		if err := ps1Script.Execute(&b, c); err != nil {
			return "", "", err
		}
		// PowerShell 5 reads a script without a BOM as the system code
		// page; the script is ASCII, so CRLF is all it needs.
		return strings.ReplaceAll(b.String(), "\n", "\r\n"), "connect-gatte.ps1", nil
	}
	return "", "", fmt.Errorf("unknown system %q", os)
}

// ---- pages

type connectPanel struct {
	Info    connectInfo
	Command string
	Scripts map[string]string
	Error   string
}

func (s *uiServer) connectPanelFor(username string) connectPanel {
	var p connectPanel
	s.uiRun(func(e *opEnv) int {
		info, err := uiConnectInfo(e.cfg, username, time.Now())
		p.Info = info
		if err != nil {
			p.Error = err.Error()
			return exitProblem
		}
		if info.Ready {
			p.Command = uiConnectCommand(info)
			p.Scripts = map[string]string{}
			for _, osName := range []string{"macos", "linux", "windows"} {
				text, _, err := uiRenderScript(info, osName)
				if err != nil {
					p.Error = err.Error()
					return exitProblem
				}
				p.Scripts[osName] = text
			}
		}
		return exitOK
	})
	return p
}

func (s *uiServer) connectPage(w http.ResponseWriter, r *http.Request) {
	u := r.URL.Query().Get("u")
	p := s.connectPanelFor(u)
	s.render(w, "connect", "Connect a computer", page{Nav: "people", Data: p, Error: p.Error})
}

// connectScript serves a script as a download. It changes nothing, so GET
// is right; it carries no secret, so nothing is lost if it is saved.
func (s *uiServer) connectScript(w http.ResponseWriter, r *http.Request) {
	p := s.connectPanelFor(r.URL.Query().Get("u"))
	if !p.Info.Ready || p.Error != "" {
		http.Error(w, "connect scripts are not configured: "+p.Info.Missing+p.Error, http.StatusNotFound)
		return
	}
	text, name, err := uiRenderScript(p.Info, r.URL.Query().Get("os"))
	if err != nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+name+`"`)
	_, _ = w.Write([]byte(text))
}

// ---- the Add person assistant

type newPerson struct {
	Step        int
	DisplayName string
	Username    string
	Email       string
	Groups      []uiGroup
	Chosen      map[string]bool
	Picked      []uiGroup
	Roles       map[string]uiRole
	Error       string
}

// uiSuggestUsername turns "Ana Souza" into "ana.souza".
func uiSuggestUsername(name string) string {
	fold := strings.NewReplacer("á", "a", "à", "a", "â", "a", "ã", "a", "ä", "a", "é", "e", "ê", "e", "è", "e", "í", "i", "î", "i",
		"ó", "o", "ô", "o", "õ", "o", "ö", "o", "ú", "u", "ü", "u", "ç", "c", "ñ", "n")
	var b strings.Builder
	dot := false
	for _, r := range fold.Replace(strings.ToLower(strings.TrimSpace(name))) {
		switch {
		case r < unicode.MaxASCII && (unicode.IsLetter(r) || unicode.IsDigit(r)):
			b.WriteRune(r)
			dot = false
		case (unicode.IsSpace(r) || r == '.' || r == '-' || r == '_') && b.Len() > 0 && !dot:
			b.WriteByte('.')
			dot = true
		}
	}
	out := strings.Trim(b.String(), ".")
	if len(out) > 64 {
		out = out[:64]
	}
	return out
}

func (s *uiServer) newPersonPage(w http.ResponseWriter, r *http.Request) {
	if s.accounts == nil {
		http.NotFound(w, r)
		return
	}
	q := r.URL.Query()
	d := newPerson{Step: 1, DisplayName: strings.TrimSpace(q.Get("displayname")), Username: strings.TrimSpace(q.Get("username")),
		Email: strings.TrimSpace(q.Get("email")), Chosen: map[string]bool{}}
	for _, g := range q["group"] {
		d.Chosen[g] = true
	}
	s.uiRun(func(e *opEnv) int {
		d.Groups = uiKnownGroups(e)
		d.Roles = map[string]uiRole{}
		for _, role := range e.cfg.Roles {
			ur := uiRole{Name: role.Name, Tools: append([]string(nil), role.Tools...)}
			for backend, tools := range role.Grants {
				for _, t := range tools {
					ur.Tools = append(ur.Tools, backend+"."+t)
				}
			}
			d.Roles[role.Name] = ur
		}
		return exitOK
	})
	switch r.URL.Path {
	case "/people/new/access", "/people/new/review":
		if d.Username == "" {
			d.Username = uiSuggestUsername(d.DisplayName)
		}
		if err := idp.ValidateAccount(idp.Account{Username: d.Username, DisplayName: d.DisplayName, Email: d.Email}); err != nil {
			d.Error = err.Error()
			break
		}
		if existing, err := s.accounts.Accounts(); err == nil {
			for _, a := range existing {
				if a.Username == d.Username {
					d.Error = fmt.Sprintf("%s is already taken by %s. Pick another username.", d.Username, a.DisplayName)
				}
			}
		}
		if d.Error != "" {
			break
		}
		d.Step = 2
		if r.URL.Path == "/people/new/review" {
			for _, g := range d.Groups {
				if d.Chosen[g.Name] {
					d.Picked = append(d.Picked, g)
				}
			}
			d.Step = 3
		}
	}
	s.render(w, "newperson", "Add a person", page{Nav: "people", Data: d, Error: visible.Escape(d.Error)})
}
