package admin

// The analyst's connect script (design/adr/0039), rendered here so that
// every front hands out the same text with the same validations: a front
// receives it ready.

import (
	"bytes"
	"context"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"strings"
	"text/template"
	"time"
	"unicode"

	"github.com/bunnyiesart/Gatte/internal/config"
	"github.com/bunnyiesart/Gatte/internal/idp"
	"github.com/bunnyiesart/Gatte/pkg/adminapi"
)

// ConnectInfo is what a connect script is made of.
type ConnectInfo struct {
	Ready bool
	// Missing is an English sentence saying what to set, and MissingKeys
	// the [connect] keys it names, when Ready is false.
	Missing     string
	MissingKeys []string
	URL         string
	MetaURL     string
	ClientID    string
	Port        int
	Server      string
	Username    string
	CAPEM       string
	Date        string
}

var safeURLRe = regexp.MustCompile(`^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?(/[A-Za-z0-9._~/-]*)?$`)

// ConnectInfoOf reads what the scripts need from the configuration. Every
// value it returns is safe inside single quotes in sh and PowerShell: the
// URL, names and client id are held to charsets without quotes, and the CA
// is parsed and re-encoded, so it can only be base64 lines.
func ConnectInfoOf(cfg *config.Config, username string, now time.Time) (ConnectInfo, error) {
	c := ConnectInfo{Server: cfg.Connect.ServerName, ClientID: cfg.Connect.ClientID, Port: cfg.Connect.CallbackPort,
		URL: cfg.OIDC.Audience, Date: now.UTC().Format("2006-01-02")}
	if c.Server == "" {
		c.Server = "gatte"
	}
	if c.ClientID == "" {
		c.MissingKeys = []string{"client_id"}
		if c.Port <= 0 {
			c.MissingKeys = append(c.MissingKeys, "callback_port")
		}
		c.Missing = "Set [connect] client_id and callback_port in the configuration file: the public OAuth client your identity provider has registered for Claude Code, and the port of its redirect URI."
		return c, nil
	}
	if !safeURLRe.MatchString(c.URL) {
		return c, fmt.Errorf("oidc.audience %q cannot go into a connect script: it must be a plain https URL", c.URL)
	}
	u, _ := url.Parse(c.URL)
	c.MetaURL = u.Scheme + "://" + u.Host + "/.well-known/oauth-protected-resource"
	if username != "" {
		if err := idp.ValidateAccount(idp.Account{Username: username, DisplayName: "x"}); err != nil {
			return c, err
		}
		c.Username = username
	}
	if cfg.Connect.CAFile != "" {
		pemText, err := canonicalCA(cfg.Connect.CAFile)
		if err != nil {
			return c, err
		}
		c.CAPEM = pemText
	}
	c.Ready = true
	return c, nil
}

// canonicalCA reads a PEM file and returns only its certificates,
// re-encoded: nothing else in the file reaches a script.
func canonicalCA(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("connect.ca_file: %w", err)
	}
	var out bytes.Buffer
	for {
		var blk *pem.Block
		blk, b = pem.Decode(b)
		if blk == nil {
			break
		}
		if blk.Type != "CERTIFICATE" {
			continue
		}
		if _, err := x509.ParseCertificate(blk.Bytes); err != nil {
			return "", fmt.Errorf("connect.ca_file: %w", err)
		}
		if err := pem.Encode(&out, &pem.Block{Type: "CERTIFICATE", Bytes: blk.Bytes}); err != nil {
			return "", err
		}
	}
	if out.Len() == 0 {
		return "", errors.New("connect.ca_file: no certificate in it")
	}
	return out.String(), nil
}

var shScript = template.Must(template.New("sh").Parse(`#!/bin/sh
# Connect Claude Code to Gatte, the team's MCP gateway.
{{if .Username}}# For {{.Username}}. {{end}}Generated by mcp-gateway ui on {{.Date}}. Contains no secret.
set -eu

GATTE_URL='{{.URL}}'

say() { printf '%s\n' "$*"; }

if ! command -v claude >/dev/null 2>&1; then
  say "Claude Code isn't installed. Install it, then run this script again:"
  say "  https://docs.claude.com/en/docs/claude-code/setup"
  exit 1
fi
{{if .CAPEM}}
# The gateway's certificate comes from the team's own certificate authority.
GATTE_DIR="$HOME/.config/gatte"
mkdir -p "$GATTE_DIR"
cat > "$GATTE_DIR/ca.pem" <<'GATTE_CA'
{{.CAPEM}}GATTE_CA
export NODE_EXTRA_CA_CERTS="$GATTE_DIR/ca.pem"
added=no
for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
  [ -f "$rc" ] || continue
  if ! grep -q 'gatte/ca.pem' "$rc"; then
    printf '\n# Gatte: trust the team certificate authority\nexport NODE_EXTRA_CA_CERTS="$HOME/.config/gatte/ca.pem"\n' >> "$rc"
  fi
  added=yes
done
if [ "$added" = no ]; then
  printf '# Gatte: trust the team certificate authority\nexport NODE_EXTRA_CA_CERTS="$HOME/.config/gatte/ca.pem"\n' >> "$HOME/.profile"
fi
say "✓ Trusted the team certificate authority"
{{end}}
if command -v curl >/dev/null 2>&1; then
  if curl -fsS{{if .CAPEM}} --cacert "$GATTE_DIR/ca.pem"{{end}} -o /dev/null --max-time 10 '{{.MetaURL}}'; then
    say "✓ Gatte answers at $GATTE_URL"
  else
    say "! Gatte didn't answer at $GATTE_URL. Are you on the VPN? Continuing anyway."
  fi
fi

claude mcp remove '{{.Server}}' --scope user >/dev/null 2>&1 || true
claude mcp add --transport http --scope user --client-id '{{.ClientID}}' --callback-port {{.Port}} '{{.Server}}' "$GATTE_URL"

say ""
say "✓ Done. Next: open a new terminal, run claude, type /mcp, choose {{.Server}}{{if .Username}},"
say "  and sign in as {{.Username}}{{end}}."
`))

var ps1Script = template.Must(template.New("ps1").Parse(`# Connect Claude Code to Gatte, the team's MCP gateway.
{{if .Username}}# For {{.Username}}. {{end}}Generated by mcp-gateway ui on {{.Date}}. Contains no secret.
# Run: powershell -ExecutionPolicy Bypass -File .\connect-gatte.ps1
$ErrorActionPreference = 'Stop'

$GatteUrl = '{{.URL}}'

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
  Write-Host "Claude Code isn't installed. Install it, then run this script again:"
  Write-Host "  https://docs.claude.com/en/docs/claude-code/setup"
  exit 1
}
{{if .CAPEM}}
# The gateway's certificate comes from the team's own certificate authority.
$GatteDir = Join-Path $env:USERPROFILE '.gatte'
New-Item -ItemType Directory -Force -Path $GatteDir | Out-Null
$Ca = Join-Path $GatteDir 'ca.pem'
@'
{{.CAPEM}}'@ | Set-Content -Path $Ca -Encoding ascii
[Environment]::SetEnvironmentVariable('NODE_EXTRA_CA_CERTS', $Ca, 'User')
$env:NODE_EXTRA_CA_CERTS = $Ca
Write-Host "Trusted the team certificate authority"
{{else}}
try {
  Invoke-WebRequest -UseBasicParsing -TimeoutSec 10 -Uri '{{.MetaURL}}' | Out-Null
  Write-Host "Gatte answers at $GatteUrl"
} catch {
  Write-Host "Gatte didn't answer at $GatteUrl. Are you on the VPN? Continuing anyway."
}
{{end}}
claude mcp remove '{{.Server}}' --scope user 2>$null | Out-Null
claude mcp add --transport http --scope user --client-id '{{.ClientID}}' --callback-port {{.Port}} '{{.Server}}' $GatteUrl

Write-Host ""
Write-Host "Done. Next: open a new terminal, run claude, type /mcp, choose {{.Server}}{{if .Username}}, and sign in as {{.Username}}{{end}}."
`))

// ConnectCommand is the one line for a machine that needs no CA.
func ConnectCommand(c ConnectInfo) string {
	return fmt.Sprintf("claude mcp add --transport http --scope user --client-id '%s' --callback-port %d '%s' '%s'", c.ClientID, c.Port, c.Server, c.URL)
}

// RenderScript renders the script for one system and names its file.
func RenderScript(c ConnectInfo, system string) (string, string, error) {
	var b bytes.Buffer
	switch system {
	case adminapi.OSMacOS, adminapi.OSLinux:
		if err := shScript.Execute(&b, c); err != nil {
			return "", "", err
		}
		return b.String(), "connect-gatte.sh", nil
	case adminapi.OSWindows:
		if err := ps1Script.Execute(&b, c); err != nil {
			return "", "", err
		}
		// PowerShell 5 reads a script without a BOM as the system code
		// page; the script is ASCII, so CRLF is all it needs.
		return strings.ReplaceAll(b.String(), "\n", "\r\n"), "connect-gatte.ps1", nil
	}
	return "", "", fmt.Errorf("unknown system %q", system)
}

// Systems is the systems a connect script exists for, and how each runs
// the file it downloads.
func Systems() []adminapi.ConnectScript {
	return []adminapi.ConnectScript{
		{OS: adminapi.OSMacOS, Name: "macOS", Filename: "connect-gatte.sh", Run: "sh ~/Downloads/connect-gatte.sh"},
		{OS: adminapi.OSLinux, Name: "Linux", Filename: "connect-gatte.sh", Run: "sh ~/Downloads/connect-gatte.sh"},
		{OS: adminapi.OSWindows, Name: "Windows", Filename: "connect-gatte.ps1", Run: `powershell -ExecutionPolicy Bypass -File "$HOME\Downloads\connect-gatte.ps1"`},
	}
}

// Connect is how an analyst connects Claude Code, with the three scripts
// rendered. Not ready, it says which [connect] keys are missing.
func (s *Service) Connect(ctx context.Context, username string) (adminapi.Connect, error) {
	cfg, err := s.config()
	if err != nil {
		return adminapi.Connect{}, err
	}
	info, err := ConnectInfoOf(cfg, username, s.d.Now())
	if err != nil {
		return adminapi.Connect{}, connectErr(err, username)
	}
	out := adminapi.Connect{Ready: info.Ready, Missing: info.MissingKeys}
	if !info.Ready {
		return out, nil
	}
	out.URL, out.ClientID, out.CallbackPort, out.ServerName = info.URL, info.ClientID, info.Port, info.Server
	out.Username, out.HasCA, out.Command = info.Username, info.CAPEM != "", ConnectCommand(info)
	for _, sys := range Systems() {
		text, _, err := RenderScript(info, sys.OS)
		if err != nil {
			return adminapi.Connect{}, adminapi.NewError(adminapi.CodeInternal, "rendering the %s script: %v", sys.Name, err)
		}
		sys.Content = text
		out.Scripts = append(out.Scripts, sys)
	}
	return out, nil
}

// ConnectScript is one script as a file.
func (s *Service) ConnectScript(ctx context.Context, system, username string) (adminapi.ConnectScript, error) {
	c, err := s.Connect(ctx, username)
	if err != nil {
		return adminapi.ConnectScript{}, err
	}
	if !c.Ready {
		return adminapi.ConnectScript{}, adminapi.NewError(adminapi.CodeConnectNotConfigured,
			"connect scripts are not configured: set [connect] %s", strings.Join(c.Missing, " and ")).With("missing", c.Missing)
	}
	for _, sc := range c.Scripts {
		if sc.OS == system {
			return sc, nil
		}
	}
	return adminapi.ConnectScript{}, adminapi.NewError(adminapi.CodeInvalidArgument, "os must be macos, linux or windows").With("field", "os")
}

func connectErr(err error, username string) error {
	if username != "" && strings.HasPrefix(err.Error(), "username") {
		return adminapi.NewError(adminapi.CodeInvalidArgument, "%v", err).With("field", "username")
	}
	return adminapi.NewError(adminapi.CodeConnectNotConfigured, "%v", err)
}

// SuggestUsername turns "Ana Souza" into "ana.souza".
func SuggestUsername(name string) string {
	fold := strings.NewReplacer("á", "a", "à", "a", "â", "a", "ã", "a", "ä", "a", "é", "e", "ê", "e", "è", "e", "í", "i", "î", "i",
		"ó", "o", "ô", "o", "õ", "o", "ö", "o", "ú", "u", "ü", "u", "ç", "c", "ñ", "n")
	var b strings.Builder
	dot := false
	for _, r := range fold.Replace(strings.ToLower(strings.TrimSpace(name))) {
		switch {
		case r < unicode.MaxASCII && (unicode.IsLetter(r) || unicode.IsDigit(r)):
			b.WriteRune(r)
			dot = false
		case (unicode.IsSpace(r) || r == '.' || r == '-' || r == '_') && b.Len() > 0 && !dot:
			b.WriteByte('.')
			dot = true
		}
	}
	out := strings.Trim(b.String(), ".")
	if len(out) > 64 {
		out = out[:64]
	}
	return out
}
