#!/usr/bin/env sh
# Jail networking for a bare-metal FreeBSD host: one private bridge, both
# jails on it as VNET, NAT for outbound.
#
# Run after deploy/newhost-bootstrap.sh, before the CA and the jails
# themselves.
#
#   JAILHOST_TRANSPORT=ssh JAILHOST_HOST=192.168.1.4 sh deploy/newhost-topology.sh
#
# # Two decisions worth reading before changing anything here
#
# **Both jails are VNET.** The previous host had one classic jail and one
# VNET jail, and that split produced the defect recorded in the CORREÇÃO
# block of design/adr/0011: a classic jail has no loopback of its own, so a
# process binding 127.0.0.1 has that bind silently rewritten to the jail's
# routable address. The gateway's requireLoopbackBind passed while the
# socket sat exposed on the network. Measured, not theorised. Making every
# jail VNET means that class of surprise cannot recur here.
#
# **The bridge is private -- it has no physical member.** Bridging onto the
# LAN would be easier and would let the workstation reach the jails
# directly, which is exactly why it is wrong: the third test phase exists
# to prove an external machine reaches the gateway *only* over the VPN. If
# the LAN can reach it too, that test proves nothing. The jails are
# deliberately unreachable except through the host, and the host only
# forwards what pf permits.
set -eu

cd "$(dirname "$0")"
. ./lib/remote.sh

BRIDGE="${JAIL_BRIDGE:-bridge0}"
JAIL_NET="${JAIL_NET:-10.17.90.0/24}"
HOST_IP="${JAIL_HOST_IP:-10.17.90.1}"
EXT_IF="${EXT_IF:-re0}"

echo "==> target: $(remote_target)"
echo "==> bridge $BRIDGE, host side $HOST_IP, jail network $JAIL_NET"

# ------------------------------------------------------------------ bridge
#
# Created persistently in rc.conf AND brought up now, so the running state
# and the boot state agree. A bridge that only exists until reboot is the
# kind of thing that works all week and vanishes on the first power cut.
echo "==> creating the bridge"
remote_sh sysrc cloned_interfaces+="$BRIDGE"
# One argument, not three. remote_sh forwards "$@" verbatim and the two
# transports both space-join argv, so local quotes are gone by the time the
# remote shell sees it: `sysrc ifconfig_bridge0="inet 10.17.90.1/24 up"`
# arrives as three words and sysrc rejects the second as a variable name.
# Passing the whole command as a single string lets the REMOTE shell do the
# quoting, which is the documented safe shape in deploy/lib/remote.sh.
remote_sh "sysrc ifconfig_${BRIDGE}='inet $HOST_IP/24 up'"

if remote_sh ifconfig "$BRIDGE" >/dev/null 2>&1; then
	echo "    $BRIDGE already exists"
else
	remote_sh ifconfig "$BRIDGE" create
fi
remote_sh ifconfig "$BRIDGE" inet "$HOST_IP/24" up || true

# --------------------------------------------------------------------- pf
#
# NAT so the jails can reach the internet (pkg, and Authelia's own needs),
# and a pass rule for traffic the host forwards between the bridge and the
# outside. Everything inbound from the LAN or the internet toward the jails
# stays blocked by the default-deny already in /etc/pf.conf -- the VPN is
# the only intended way in, and its rules come with the VPN.
#
# Written as a separate anchor-ish block appended once, rather than
# rewriting pf.conf, so the SSH rule that is keeping this session alive is
# never rebuilt from scratch.
echo "==> writing the full pf ruleset (NAT + filtering, in pf's required order)"
# The whole file is regenerated rather than appended to, because pf demands
# a fixed section order -- options, normalization, queueing, translation,
# filtering -- and rejects the ruleset outright if a `nat` line appears
# after a `pass`. Appending a NAT block to a file that already had filter
# rules produced exactly that:
#
#   /etc/pf.conf:35: Rules must be in order: options, ethernet,
#   normalization, queueing, translation, filtering
#
# Built locally and copied up rather than heredoc'd through the transport:
# deploy/lib/remote.sh is explicit that a quoted shell snippet with embedded
# newlines is the one call-site shape that does not survive argument
# flattening, and a pf.conf mangled in transit would be a poor thing to
# debug over the SSH session that pf.conf governs.
RULES="$(mktemp -t pfconf)"
trap 'rm -f "$RULES"' EXIT INT TERM
cat > "$RULES" <<EOF
# Firewall for the jail host. Default-deny inbound.
# Generated by deploy/newhost-topology.sh -- edit there, not here.
#
# Written after finding sshd bound to a globally-routable IPv6 address the
# ISP router hands out by autoconf: reachable from the internet or not
# depending entirely on that router, which is not a control. The gateway
# this host exists to run refuses any non-loopback bind (ADR-0011); leaving
# its host open would be incoherent.

ext_if    = "$EXT_IF"
bridge_if = "$BRIDGE"
lan_v4    = "192.168.1.0/24"
jail_net  = "$JAIL_NET"

set skip on lo0

# --- translation (must precede filtering; pf enforces this) -------------
# Outbound NAT so jails can reach the internet for packages. This opens no
# inbound path: the block-in below still denies everything not named.
nat on \$ext_if inet from \$jail_net to any -> (\$ext_if)

# --- filtering -----------------------------------------------------------
block in all
pass out all keep state

# ICMP both families. icmp6 is NOT optional: IPv6 neighbour discovery runs
# over it, and blocking it breaks IPv6 in ways that look like routing bugs.
pass in inet proto icmp all
pass in inet6 proto icmp6 all

# DHCP replies, until the static address in rc.conf takes effect at reboot.
pass in on \$ext_if inet proto udp from any port 67 to any port 68 keep state

# SSH from the local network only. This is what closes the public IPv6
# exposure: no rule permits inbound from anywhere else.
pass in on \$ext_if inet proto tcp from \$lan_v4 to (\$ext_if) port 22 keep state

# Traffic on the private jail bridge, and the jails' way out. Note there is
# deliberately no rule letting the LAN reach the jail network: the VPN is
# the only intended path in, and it brings its own rules.
pass on \$bridge_if all
pass out on \$ext_if inet from \$jail_net to any keep state
EOF

remote_cp "$RULES" /tmp/pf.conf.new
remote_sh 'mv /tmp/pf.conf.new /etc/pf.conf'

echo "==> validating pf ruleset"
remote_sh pfctl -n -f /etc/pf.conf

echo "==> loading pf ruleset"
remote_sh pfctl -f /etc/pf.conf

echo
echo "==> bridge and NAT in place. Next: create the jails, then"
echo "    deploy/soc-ca-bootstrap.sh, deploy/authelia-jail.sh, deploy/gateway-serve.sh"
