#!/bin/sh
# Runs on the Mac. End to end:
#
#   1. copies deploy/openvpn-vm-setup.sh into the jailmachine VM and runs it
#      (installs openvpn, builds the VPN PKI, writes the server config,
#      turns on IP forwarding, starts the service)
#   2. pulls the CA / client cert / client key / tls-crypt key back out and
#      assembles a single inline-everything .ovpn profile
#   3. adds the gvproxy udp/1194 forward
#
# Idempotent: re-running reuses the existing PKI and rewrites the profile.
#
# The profile is written OUTSIDE this repository on purpose -- it carries an
# unencrypted private key. Default location:
#
#   ~/.config/mcp-gateway-lab/openvpn/mcp-gateway-lab.ovpn
#
# See deploy/openvpn-access.md.
set -eu

# shellcheck source=deploy/lib/remote.sh
. "$(dirname "$0")/lib/remote.sh"

CLIENT_NAME="${CLIENT_NAME:-mac-client}"
PROFILE_DIR="${OVPN_PROFILE_DIR:-$HOME/.config/mcp-gateway-lab/openvpn}"
PROFILE="$PROFILE_DIR/mcp-gateway-lab.ovpn"
VPN_DIR=/usr/local/etc/openvpn
REMOTE_SCRIPT=/tmp/openvpn-vm-setup.sh

cd "$(dirname "$0")/.."

case "$PROFILE_DIR" in
"$PWD"|"$PWD"/*)
	echo "!! refusing to write the profile inside the repository ($PROFILE_DIR)." >&2
	echo "   It contains a private key. Set OVPN_PROFILE_DIR somewhere else." >&2
	exit 1
	;;
esac

echo "==> copying the setup script into $(remote_target)"
remote_cp deploy/openvpn-vm-setup.sh "$REMOTE_SCRIPT"

echo "==> running it on the jail host"
remote_sh sh "$REMOTE_SCRIPT"

echo "==> fetching client credentials"
mkdir -p "$PROFILE_DIR"
chmod 700 "$PROFILE_DIR"

fetch() { remote_sh cat "$1"; }

CA=$(fetch "$VPN_DIR/pki/ca.crt")
CRT=$(fetch "$VPN_DIR/pki/issued/$CLIENT_NAME.crt")
KEY=$(fetch "$VPN_DIR/pki/private/$CLIENT_NAME.key")
TC=$(fetch "$VPN_DIR/tls-crypt.key")

# The issued .crt carries a human-readable text dump before the PEM block;
# keep only the PEM so the inline <cert> block is exactly a certificate.
CRT=$(printf '%s\n' "$CRT" | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p')

for v in "$CA" "$CRT" "$KEY" "$TC"; do
	[ -n "$v" ] || { echo "!! empty credential pulled from the VM -- aborting" >&2; exit 1; }
done

# Where the client dials. On the local VM that is the Mac's own loopback,
# because gvproxy forwards it in; on a real jail host it is the host itself
# and there is no forwarder in the path at all.
case "$JAILHOST_TRANSPORT" in
jailmachine)
	OVPN_REMOTE_HOST=127.0.0.1
	OVPN_REMOTE_NOTE="# 127.0.0.1 is not a typo: gvproxy forwards the Mac's loopback udp/1194
# into the VM. Bring the forward up with deploy/openvpn-forward.sh up."
	;;
ssh)
	OVPN_REMOTE_HOST="$JAILHOST_HOST"
	OVPN_REMOTE_NOTE="# The jail host directly -- no gvproxy forwarder in the path.
# udp/1194 must be reachable from here (check the host firewall)."
	;;
esac

echo "==> writing $PROFILE"
umask 077
cat >"$PROFILE" <<EOF
# mcp-gateway lab VPN -- generated by deploy/openvpn-setup.sh
# CONTAINS A PRIVATE KEY. Do not copy this into the repository.
client
dev tun
proto udp4

$OVPN_REMOTE_NOTE
remote $OVPN_REMOTE_HOST 1194

resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM
tls-version-min 1.2
verb 3

<ca>
$CA
</ca>
<cert>
$CRT
</cert>
<key>
$KEY
</key>
<tls-crypt>
$TC
</tls-crypt>
EOF
chmod 600 "$PROFILE"

# The forward exists only because gvproxy sits between the Mac and the local
# VM. It is a jailmachine artifact -- deploy/openvpn-forward.sh talks to the
# gvproxy API socket and has no meaning against any other host.
if [ "$JAILHOST_TRANSPORT" = jailmachine ]; then
	echo "==> adding the gvproxy udp forward"
	sh deploy/openvpn-forward.sh up
else
	echo "==> skipping the gvproxy forward (JAILHOST_TRANSPORT=$JAILHOST_TRANSPORT):"
	echo "    the client dials $OVPN_REMOTE_HOST:1194 directly. Open udp/1194 on"
	echo "    the jail host's firewall yourself if it is not already."
fi

cat <<EOF

==> done.

profile: $PROFILE

Connect (needs root -- it creates a utun device and installs a route):

    sudo openvpn --config "$PROFILE"

Then, in another terminal:

    ping -c 3 10.17.89.20      # authelia, classic jail
    ping -c 3 10.17.90.10      # mcp-gateway, VNET jail
    nc -vz 10.17.90.10 443

Undo everything: deploy/openvpn-teardown.sh
EOF
