#!/bin/sh
# Runs INSIDE the jailmachine FreeBSD VM, as root. Not meant to be run on the
# Mac -- deploy/openvpn-setup.sh copies this in and executes it.
#
# Stands up an OpenVPN server on the VM host (not in a jail: it has to route
# into the jail subnet, and a non-VNET jail cannot hold a tun device or a
# routing table of its own), with its own easy-rsa PKI.
#
# Idempotent. Re-running it does not regenerate the CA, does not reissue
# certificates that already exist, and does not duplicate rc.conf or
# sysctl.conf lines. It DOES rewrite openvpn.conf from the template below and
# restart the service, so local edits to that file are lost on a re-run.
#
# See deploy/openvpn-access.md for why each piece is here.
set -eu

VPN_DIR=/usr/local/etc/openvpn
PKI_DIR="$VPN_DIR/pki"
CLIENT_NAME="${CLIENT_NAME:-mac-client}"
VPN_NET=10.8.0.0
VPN_MASK=255.255.255.0
JAIL_NET=10.17.89.0
JAIL_MASK=255.255.255.0

say() { echo "==> $*"; }

# ---------------------------------------------------------------- packages
if ! pkg info -e openvpn >/dev/null 2>&1 || ! pkg info -e easy-rsa >/dev/null 2>&1; then
	say "installing openvpn + easy-rsa"
	pkg install -y openvpn easy-rsa
else
	say "openvpn + easy-rsa already installed"
fi

# ---------------------------------------------------------------------- PKI
#
# This CA exists ONLY to authenticate VPN peers. It is deliberately NOT the
# internal TLS CA that signs the jails' web certificates -- see
# deploy/openvpn-access.md, "Two CAs, on purpose".
mkdir -p "$VPN_DIR"
chmod 750 "$VPN_DIR"

export EASYRSA_PKI="$PKI_DIR"
export EASYRSA_BATCH=1
export EASYRSA_ALGO=ec
export EASYRSA_CURVE=prime256v1
export EASYRSA_CA_EXPIRE=3650
export EASYRSA_CERT_EXPIRE=825

# NB: EASYRSA_REQ_CN is deliberately NOT exported. easy-rsa applies it to every
# request it builds, so exporting it stamps the CA's own name onto the server
# and client certificates too, and you end up unable to tell the three apart in
# a log. Pass it per-command instead.
if [ ! -f "$PKI_DIR/ca.crt" ]; then
	say "initialising easy-rsa PKI at $PKI_DIR"
	easyrsa init-pki
	EASYRSA_REQ_CN="mcp-gateway-lab-vpn-ca" easyrsa build-ca nopass
else
	say "PKI already present at $PKI_DIR (leaving CA alone)"
fi

if [ ! -f "$PKI_DIR/issued/server.crt" ]; then
	say "issuing server certificate"
	easyrsa build-server-full server nopass
else
	say "server certificate already issued"
fi

if [ ! -f "$PKI_DIR/issued/$CLIENT_NAME.crt" ]; then
	say "issuing client certificate: $CLIENT_NAME"
	easyrsa build-client-full "$CLIENT_NAME" nopass
else
	say "client certificate $CLIENT_NAME already issued"
fi

# tls-crypt wraps the whole TLS control channel in a static key. Without it,
# anything that can reach udp/1194 can start a TLS handshake; with it, packets
# that do not authenticate against this key are dropped before any TLS state is
# allocated. Cheap, and this port is reachable from the Mac's loopback.
if [ ! -f "$VPN_DIR/tls-crypt.key" ]; then
	say "generating tls-crypt key"
	openvpn --genkey secret "$VPN_DIR/tls-crypt.key"
fi
chmod 600 "$VPN_DIR/tls-crypt.key"
chmod -R go-rwx "$PKI_DIR/private"

# ------------------------------------------------------------ server config
say "writing $VPN_DIR/openvpn.conf"
cat >"$VPN_DIR/openvpn.conf" <<EOF
# Generated by deploy/openvpn-vm-setup.sh -- edits are overwritten on re-run.
dev tun
proto udp4
port 1194
topology subnet
server $VPN_NET $VPN_MASK

# The whole point: hand the client a route into the jail subnet. Note there is
# deliberately no redirect-gateway -- the Mac's normal internet traffic must
# not come through here. This tunnel is the only route to 10.17.89.0/24 and
# nothing else.
push "route $JAIL_NET $JAIL_MASK"

ca $PKI_DIR/ca.crt
cert $PKI_DIR/issued/server.crt
key $PKI_DIR/private/server.key
dh none
tls-crypt $VPN_DIR/tls-crypt.key

data-ciphers AES-256-GCM
tls-version-min 1.2

keepalive 10 60
persist-key
persist-tun

# Drop privileges after the tun device and the socket are open. This is only
# safe with DCO off, and DCO is on by default in OpenVPN 2.7 -- see below.
user openvpn
group openvpn

# Not a preference: with ovpn-dco (2.7's in-kernel data path) the server keeps
# issuing privileged ioctls for the lifetime of the process, so it cannot run
# as an unprivileged user. Leaving both on looks fine at startup and then dies
# the instant a client connects:
#
#   Failed to poll for packets: Operation not permitted (errno=1)
#   MULTI_sva: pool returned IPv4=10.8.0.2
#   Failed to create new peer: Operation not permitted (errno=1)
#   Exiting due to fatal error
#
# The client's TLS handshake completes, then it waits forever for a PUSH_REPLY
# that no longer has a server to come from. So it is DCO or the privilege
# drop, not both. This lab picks the privilege drop: a userspace data path is
# far more throughput than a couple of jails on a loopback will ever need, and
# the alternative is an internet-reachable process running as root.
disable-dco

# The client reaches this server through gvproxy's userspace UDP forwarder,
# which is a NAT. If it ever rebinds the source port mid-session the session
# would otherwise drop; float lets the server follow it. Safe here only
# because tls-crypt authenticates every packet before it is looked at.
float

explicit-exit-notify 1
verb 3
status /var/log/openvpn-status.log
log-append /var/log/openvpn.log
EOF
chmod 600 "$VPN_DIR/openvpn.conf"

# ------------------------------------------------------- forwarding + boot
#
# Persistent. sysctl.conf is read on the way to multi-user, so this survives a
# VM reboot; the sysctl call applies it now without one.
if ! grep -q '^net.inet.ip.forwarding=1' /etc/sysctl.conf 2>/dev/null; then
	say "enabling net.inet.ip.forwarding persistently"
	printf '\n# VPN clients on 10.8.0.0/24 need to be routed into the jail\n# subnet 10.17.89.0/24 -- see deploy/openvpn-access.md\nnet.inet.ip.forwarding=1\n' >>/etc/sysctl.conf
else
	say "net.inet.ip.forwarding already in /etc/sysctl.conf"
fi
sysctl net.inet.ip.forwarding=1 >/dev/null

if ! grep -q '^openvpn_enable=' /etc/rc.conf 2>/dev/null; then
	say "enabling openvpn at boot"
	sysrc openvpn_enable="YES" >/dev/null
	sysrc openvpn_configfile="$VPN_DIR/openvpn.conf" >/dev/null
else
	say "openvpn already enabled in rc.conf"
fi

# ------------------------------------------------------------------ service
say "(re)starting openvpn"
service openvpn stop >/dev/null 2>&1 || true

# An openvpn that died on a fatal error leaves its tun interface behind, and
# the next start then fails to name its own device and silently lands on a
# different one. Only interfaces in the "openvpn" group are touched, and only
# with no openvpn process running, so this cannot take out anything else.
if ! pgrep -q openvpn; then
	for _ifc in $(ifconfig -g openvpn 2>/dev/null); do
		say "destroying stale tun interface $_ifc"
		ifconfig "$_ifc" destroy || true
	done
fi

service openvpn start

sleep 2
if ! service openvpn status >/dev/null 2>&1; then
	echo "!! openvpn did not come up -- last 30 lines of /var/log/openvpn.log:" >&2
	tail -30 /var/log/openvpn.log >&2 || true
	exit 1
fi

say "openvpn is running"
sockstat -4 -l | grep -E ':1194' || { echo "!! nothing listening on udp/1194" >&2; exit 1; }
netstat -rn -f inet | grep -E '10\.8\.0|10\.17\.89' || true
say "done"
