#!/bin/sh
# Runs INSIDE the `authelia` jail, via `bastille cmd`. Driven by
# deploy/vm/authelia-host-setup.sh -- do not run it by hand.
#
# Generates every secret, writes the Authelia and nginx configuration,
# creates the two test users, and starts both daemons.
#
# Idempotent in the way that matters: a secret that already exists is never
# regenerated, because regenerating the OIDC signing key silently
# invalidates every token already issued and every JWKS a client cached.
# Configuration files, by contrast, are always rewritten from the staged
# copies -- the repo is the source of truth for those.
set -eu

STAGE="${1:-/root/provision}"
ETC=/usr/local/etc
SECRETS="$ETC/authelia/secrets"
CFG="$ETC/authelia.yml"
USERS="$ETC/authelia/users_database.yml"

CLIENT_ID=mcp-gateway
AUDIENCE='https://mcp.soc.internal/'

# ------------------------------------------------------------------ layout
mkdir -p "$ETC/authelia" "$SECRETS" /var/db/authelia /var/log/authelia \
	"$ETC/nginx/tls" /var/log/nginx
chmod 0700 "$SECRETS"
chmod 0750 "$ETC/authelia"
chmod 0700 /var/db/authelia

# ----------------------------------------------------------------- secrets
# Every value below is generated here, in the jail, on first run. None of
# them is in the repository and none of them is copied back out to the Mac.
# `openssl rand -hex 32` is 64 hex characters == 256 bits of entropy.
gen_hex() {
	f="$SECRETS/$1"
	if [ ! -s "$f" ]; then
		( umask 077; openssl rand -hex 32 >"$f" )
		echo "  generated $f"
	else
		echo "  keeping   $f"
	fi
	chmod 0600 "$f"
}

echo "==> secrets"
gen_hex session.secret
gen_hex storage.encryption.key
gen_hex identity_validation.jwt.secret
gen_hex oidc.hmac.secret

# The OIDC issuer signing key. PKCS#8 PEM, which is the form Authelia's
# `jwks[].key` wants; `openssl genrsa` alone emits PKCS#1 on some builds.
JWKS="$SECRETS/oidc.jwks.main.pem"
if [ ! -s "$JWKS" ]; then
	( umask 077; openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 \
		-out "$JWKS" 2>/dev/null )
	echo "  generated $JWKS"
else
	echo "  keeping   $JWKS"
fi
chmod 0600 "$JWKS"

# The client secret exists twice on purpose: Authelia stores only the PBKDF2
# digest, but deploy/authelia-verify.sh has to present the cleartext at the
# token endpoint the way the gateway's own client would. Both files are
# 0600 and jail-local.
CS_PLAIN="$SECRETS/oidc.client.$CLIENT_ID.plain"
CS_DIGEST="$SECRETS/oidc.client.$CLIENT_ID.digest"
if [ ! -s "$CS_PLAIN" ] || [ ! -s "$CS_DIGEST" ]; then
	( umask 077
	  openssl rand -hex 32 >"$CS_PLAIN"
	  authelia crypto hash generate pbkdf2 --variant sha512 \
		--password "$(cat "$CS_PLAIN")" | sed 's/^Digest: //' >"$CS_DIGEST" )
	echo "  generated $CS_PLAIN and its pbkdf2-sha512 digest"
else
	echo "  keeping   $CS_PLAIN"
fi
chmod 0600 "$CS_PLAIN" "$CS_DIGEST"

# ------------------------------------------------------------- test users
# Two users in two groups, because the gateway maps group -> role and one
# group proves nothing about the mapping.
mkuser() {
	_u="$1"
	_p="$SECRETS/user.$_u.plain"
	_h="$SECRETS/user.$_u.argon2"
	if [ ! -s "$_p" ] || [ ! -s "$_h" ]; then
		( umask 077
		  openssl rand -hex 16 >"$_p"
		  authelia crypto hash generate argon2 \
			--password "$(cat "$_p")" | sed 's/^Digest: //' >"$_h" )
		echo "  generated credentials for $_u"
	else
		echo "  keeping   credentials for $_u"
	fi
	chmod 0600 "$_p" "$_h"
}

echo "==> test users"
mkuser analyst
mkuser dfirlead

ANALYST_HASH=$(cat "$SECRETS/user.analyst.argon2")
DFIRLEAD_HASH=$(cat "$SECRETS/user.dfirlead.argon2")

( umask 037; cat >"$USERS" <<EOF
---
# GENERATED by deploy/vm/authelia-provision.sh -- do not edit in place.
# The hashes are argon2id, produced by \`authelia crypto hash generate\`.
# The cleartext passwords live in $SECRETS/user.*.plain, 0600, jail-local.
users:
  analyst:
    disabled: false
    displayname: 'SOC Analyst One'
    password: '${ANALYST_HASH}'
    email: 'analyst@soc.internal'
    groups:
      - 'soc-analysts'
  dfirlead:
    disabled: false
    displayname: 'DFIR Lead One'
    password: '${DFIRLEAD_HASH}'
    email: 'dfirlead@soc.internal'
    groups:
      - 'dfir-leads'
      - 'soc-analysts'
EOF
)
chown root:www "$USERS" 2>/dev/null || true
chmod 0640 "$USERS"
echo "  wrote $USERS"

# ----------------------------------------------------- configuration files
echo "==> configuration"
install -m 0640 "$STAGE/authelia-configuration.yml" "$CFG"
install -m 0644 "$STAGE/authelia-nginx.conf" "$ETC/nginx/nginx.conf"
echo "  wrote $CFG and $ETC/nginx/nginx.conf"

# The TLS material was issued by the CA on the VM host and dropped into
# $ETC/nginx/tls by the host-side script. Fail loudly rather than starting
# nginx on a certificate that is not there.
for f in "$ETC/nginx/tls/id.soc.internal.crt" "$ETC/nginx/tls/id.soc.internal.key"; do
	[ -s "$f" ] || { echo "provision: missing $f" >&2; exit 1; }
done
chmod 0644 "$ETC/nginx/tls/id.soc.internal.crt"
chmod 0600 "$ETC/nginx/tls/id.soc.internal.key"

# --------------------------------------------------------------- validate
echo "==> validating the Authelia configuration"
authelia validate-config --config "$CFG" --config.experimental.filters template

echo "==> validating the nginx configuration"
nginx -t

# ----------------------------------------------------------------- service
echo "==> services"
sysrc -f /etc/rc.conf authelia_enable=YES >/dev/null
sysrc -f /etc/rc.conf nginx_enable=YES >/dev/null

service authelia restart >/dev/null 2>&1 || service authelia start
service nginx restart >/dev/null 2>&1 || service nginx start

# Authelia opens its listener a beat after the process starts; without this
# the first verify run races it and reports a connection refused that has
# nothing to do with the configuration.
i=0
while [ $i -lt 30 ]; do
	if fetch -qo /dev/null "http://127.0.0.1:9091/api/health" 2>/dev/null; then break; fi
	i=$((i + 1))
	sleep 1
done

service authelia status || true
service nginx status || true
echo "==> provisioned. client_id=$CLIENT_ID audience=$AUDIENCE"
